apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcgis-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: {{ include "arcgis-server.name" . }}

