apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcgis-server.fullname" . }}
  labels:
    app: arcgis-server
    monitoring: enabled
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: metrics
      port: 9121
      targetPort: metrics
  selector:
    app.kubernetes.io/name: arcgis-server

