replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "7.2"

service:
  type: NodePort
  port: 6379

serviceAccount:
  create: false

resources: {}

metrics:
  enabled: true
  exporter:
    image: bitnami/redis-exporter:latest
    port: 9121
    redis_uri: redis://localhost:6379

