grafana:
  adminPassword: admin123
  service:
    type: ClusterIP
  serviceMonitor:
    selfMonitor: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        memory: "200Mi"
        cpu: "100m"

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: General

