apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arcgis-portal
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: arcgis-portal
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s

