apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arcgis-server
  labels:
    release: monitoring
spec:
  selector:
    matchLabels
      monitoring: enabled
      app: arcgis-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
