replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80

serviceAccount:
  create: false

resources: {}

metrics:
  enabled: true
  exporter:
    image: nginx/nginx-prometheus-exporter:latest
    port: 9113
    scrape_uri: http://localhost/status

