spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: arcgis-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arcgis-portal
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        {{- if .Values.metrics.enabled }}
        - name: nginx-exporter
          image: "{{ .Values.metrics.exporter.image }}"
          args:
            - -nginx.scrape-uri
            - {{ .Values.metrics.exporter.scrape_uri }}
          ports:
            - containerPort: {{ .Values.metrics.exporter.port }}
              name: metrics
        {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: arcgis-portal-nginx-config

