apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcgis-portal.fullname" . }}
  labels:
    app: arcgis-portal
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113  # safer unless you're explicitly naming the port in deployment
  selector:
    app.kubernetes.io/name: arcgis-portal

