apiVersion: v1
kind: Service
metadata:
  name: {{ include "arcgis-portal.fullname" . }}
  labels:
    app: arcgis-portal
    monitoring: enabled
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113  
  selector:
    app.kubernetes.io/name: arcgis-portal

