name: Destroy Helm Releases

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name arcgis-eks

      - name: Uninstall Helm Releases
        run: |
          helm uninstall arcgis-portal --namespace default || true
          helm uninstall arcgis-server --namespace default || true

